# Site settings
title: 徐凯强的博客
email: 1977615442@qq.com
description: > # this means to ignore newlines until "baseurl:"
  这是我的第一个github pages 根据  jekyll 搭建的静态网站,希望可以越来越好,加油.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://supermanxkq.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  supermanxkq

# Build settings
markdown: kramdown


